---
title: "stan basic"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---




```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidybayes)
library(rstan)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```


## 模拟

```{r, warning=FALSE, message=FALSE}
stan_program <- "
parameters {
   real alpha;
}

model {
  target += normal_lpdf(alpha| 0, 1);
}
"

model <- stan(model_code = stan_program)
```


```{r}
model %>% 
  tidybayes::gather_draws(alpha) %>% 
  ungroup() %>% 
  ggplot(aes(x = .value)) +
  geom_histogram(color = "white")
```



## 一个参数

如果我们模拟一个数据，看stan能否捕获还原？

```{r}
y <- rpois(100, lambda = 6)

d <- tibble(y = y)
d
```





```{r, warning=FALSE, message=FALSE}
stan_program <- "
data {
  int N;
  int y[N];
}
parameters {
   real log_lambda;
}

model {
  target += poisson_log_lpmf(y | log_lambda);
  target += normal_lpdf(log_lambda | 1, 2);

}
"
stan_data <- list(
   N = nrow(d),
   y = d$y
  )

model <- stan(model_code = stan_program, data = stan_data)
```



```{r, fig.asp = 0.618, fig.width= 5}
model %>%
  tidybayes::spread_draws(log_lambda) %>%
  ggplot(aes(x = log_lambda)) +
  tidybayes::stat_halfeye(
    fill = "skyblue",
    .width = c(0.66, 0.95),
    interval_colour = "red",
    point_colour = "red",
  ) 
```



## 两个参数

```{r}
y <- rnorm(100, mean = 20, sd = 4)

d <- tibble(y = y)
d
```



```{r, warning=FALSE, message=FALSE}
stan_program <- "
data {
  int N;
  vector[N] y;
}
parameters {
   real alpha;
   real<lower=0> sigma;
}

model {
  target += normal_lpdf(y | alpha, sigma);
  target += normal_lpdf(alpha | 0, 5);
  target += cauchy_lpdf(sigma | 0, 1);
  
}
"
stan_data <- list(
   N = nrow(d),
   y = d$y
  )

model <- stan(model_code = stan_program, data = stan_data)
```



```{r, fig.asp = 0.618, fig.width= 8}
model %>%
  tidybayes::gather_draws(alpha, sigma) %>%
  ggplot(aes(x = .value)) +
  tidybayes::stat_halfeye(
    fill = "skyblue",
    .width = c(0.66, 0.95),
    interval_colour = "red",
    point_colour = "red",
  ) +
  facet_wrap(vars(.variable), scales = "free") 
```



